# Site settings
title: Kashish Grover - Web Developer
description: "Kashish Grover is a Software Developer, Photographer, and a Percussionist from Delhi, India."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kashish.xyz"

# User settings
username: kashishgrover
user_title: Software Developer | Photographer | Percussionist
email: kashishgrover95@gmail.com
twitter_username: kashishgrover95
github_username:  kashishgrover
gplus_username:  +kashishgrover
facebook_username: kashishgrover

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: About me
    url: /about
# projects in header index
projects:
  - name: asciilang
    url: https://github.com/victorvoid/asciilang
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
